pipeline {
    agent ubuild
    environment {
        REDMINE_API_KEY = "80352e51c41c38850d2d5cf1ac2e51c9c0e611e1"
        REDMINE_URL = "https://redmine.e-legion.com"
        KEYSTORE = "/home/gitlab-runner/android/release.jks"
        STOREPASS = "m94n923kad0185zp"
        KEYALIAS = "elegionandroidmarket"
        KEYPASS = "apm06bfgy49aket000"
        RELEASE_KEYSTORE = "/home/gitlab-runner/android/release.jks"
        RELEASE_STOREPASS = "m94n923kad0185zp"
        RELEASE_KEYALIAS = "elegionandroidmarket"
        RELEASE_KEYPASS = "apm06bfgy49aket000"
        HOCKEY_APP_TOKEN = "55a90241ac8c46e6baae96e6f94eae3d"
        RELEASE_FABRIC_API_KEY = "aba301d58d2ab586a56e281861dd14141b362b34"
        RELEASE_FABRIC_API_SECRET = "a896e777cae983a61bc57b2024bec131e975dce43eebc223bbc343b8f0f46a64"
        RELEASE_QA_FABRIC_API_KEY = "aba301d58d2ab586a56e281861dd14141b362b34"
        RELEASE_QA_FABRIC_API_SECRET = "a896e777cae983a61bc57b2024bec131e975dce43eebc223bbc343b8f0f46a64"
        REASSIGN_QA_ID = "591"
    }
    options {
        gitLabConnection("https://gitlab.e-legion.com")
    }
    triggers {
        gitlab(
            triggerOnPush: true,
            triggerOnMergeRequest: false,
            branchFilterType: 'All'
        )
    }
    stages {
        stage('verification') {
            when {
                not {
                    branch 'master'
                }
            }
            steps {
                sh './gradlew clean ktlint detektCheck lintDebug testDebugUnitTest --stacktrace'
                archiveArtifacts 'app/build/reports/ktlint/ktlint.xml, app/build/reports/detekt/detekt-report.html, app/build/reports/lint-results-debug.html, app/build/reports/tests/testDebugUnitTest/'
            }
        }
    }
}